build: stabilize OneCloud OpenClash firmware

diff --git a/devices/common/patches/base-files.patch b/devices/common/patches/base-files.patch
--- a/devices/common/patches/base-files.patch
+++ b/devices/common/patches/base-files.patch
@@ -1,20 +1,6 @@
---- a/package/base-files/files/etc/rc.common
-+++ b/package/base-files/files/etc/rc.common
-@@ -28,7 +28,9 @@ restart() {
- }
- 
- boot() {
--	start "$@"
-+	name="$(basename "${initscript}")"
-+	name="${name##S[0-9][0-9]}"
-+	[[ "$(uci -q get $name.$name[0].enabled)" == 0 || "$(uci -q get $name.config.enabled)" == 0 || "$(uci -q get $name.$name.enabled)" == 0 || "$(uci -q get $name.main.enabled)" == 0 || "$(uci -q get $name.$name[0].enable)" == 0 || "$(uci -q get $name.config.enable)" == 0 || "$(uci -q get $name.$name.enable)" == 0 || "$(uci -q get $name.main.enable)" == 0 ]] || start "$@";
- }
- 
- shutdown() {
-
 --- a/package/base-files/files/lib/functions.sh
 +++ b/package/base-files/files/lib/functions.sh
-@@ -395,7 +395,9 @@ default_postinst() {
+@@ -395,10 +395,13 @@ default_postinst() {
  			if [ "$PKG_UPGRADE" != "1" ]; then
  				"$i" enable
  			fi
@@ -25,58 +11,64 @@
  		fi
  	done
 
++	[ -x /etc/init.d/ucitrack ] && /etc/init.d/ucitrack reload
+ 	return $ret
+ }
+
+
 --- a/package/base-files/files/etc/shinit
 +++ b/package/base-files/files/etc/shinit
 @@ -2,6 +2,8 @@
  [ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi
- 
+
  alias ll='ls -alF --color=auto'
 +alias reboot='(/bin/busybox reboot &);sleep 3;/bin/busybox reboot -f'
 +PS1='\[\e[32m\][\[\e[m\]\[\e[31m\]\u\[\e[m\]\[\e[33m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\]:\[\e[m\]\[\e[32m\]\[\e[1;32m\]\@\[\e[36m\] \w\[\e[m\]\[\e[32m\]]\[\e[0m\] \$\[\e[m\] '
- 
+
  [ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc
 
 --- a/package/base-files/files/sbin/sysupgrade
 +++ b/package/base-files/files/sbin/sysupgrade
-@@ -277,13 +277,15 @@ create_backup_archive() {
- 		# Part of archive with installed packages info
- 		if [ $ret -eq 0 ]; then
- 			if [ "$SAVE_INSTALLED_PKGS" -eq 1 ]; then
--				# Format: pkg-name<TAB>{rom,overlay,unknown}
--				# rom is used for pkgs in /rom, even if updated later
--				tar_print_member "$INSTALLED_PACKAGES" "$(find /usr/lib/opkg/info -name "*.control" \( \
--					\( -exec test -f /rom/{} \; -exec echo {} rom \; \) -o \
--					\( -exec test -f /overlay/upper/{} \; -exec echo {} overlay \; \) -o \
--					\( -exec echo {} unknown \; \) \
--					\) | sed -e 's,.*/,,;s/\.control /\t/')" || ret=1
-+				. /etc/profile.d/opkg.sh && opkg save
-+				[ -f /rom/etc/uci-defaults/zz-asu-defaults ] && {
-+				cp -f /rom/etc/uci-defaults/zz-asu-defaults /etc/uci-defaults/zz-asu-defaults
-+				echo "/etc/uci-defaults/zz-asu-defaults" >> $CONFFILES
-+				}
+@@ -296,11 +296,7 @@ create_backup_archive() {
+ 				# Format: pkg-name<TAB>{rom,overlay,unknown}
+ 				# rom is used for pkgs in /rom, even if updated later
+ 				if [ -d "/usr/lib/opkg/info" ]; then
+-					tar_print_member "$INSTALLED_PACKAGES" "$(find /usr/lib/opkg/info -name "*.control" \( \
+-						\( -exec test -f /rom/{} \; -exec echo {} rom \; \) -o \
+-						\( -exec test -f /overlay/upper/{} \; -exec echo {} overlay \; \) -o \
+-						\( -exec echo {} unknown \; \) \
+-						\) | sed -e 's,.*/,,;s/\.control /\t/')" || ret=1
++					. /etc/profile.d/opkg.sh && opkg save
+ 				elif [ -d "/lib/apk/packages" ]; then
+ 					tar_print_member "$INSTALLED_PACKAGES" "$(find /lib/apk/packages -name "*.list" \( \
+ 						\( -exec test -f /rom/{} \; -exec echo {} rom \; \) -o \
+@@ -311,6 +307,10 @@ create_backup_archive() {
+ 					echo "Failed to detect installed packages metadata files." >&2
+ 					ret=1
+ 				fi
 +			else
 +				uci -q del opkg.auto
 +				uci -q del opkg.custom
 +				uci commit opkg
  			fi
  		fi
- 
+
 
 --- a/package/base-files/files/etc/profile
 +++ b/package/base-files/files/etc/profile
-@@ -22,7 +23,11 @@ esac
- 
- [ -n "$FAILSAFE" ] || {
- 	for FILE in /etc/profile.d/*.sh; do
--		[ -e "$FILE" ] && . "$FILE"
+@@ -33,7 +33,11 @@ esac
+ if [ -z "$FAILSAFE" ] ; then
+ 	for FILE in /etc/profile.d/*.sh ; do
+ 		[ -f "${FILE%.sh}.hush" ] && continue
+-		[ -f "$FILE" ] && . "$FILE"
 +		if [ "$FILE" == "/etc/profile.d/30-sysinfo.sh" ]; then
 +		 [ "$(which bash)" ] && env -i bash "$FILE"
 +		else
-+		 [ -e "$FILE" ] && . "$FILE"
++		 [ -f "$FILE" ] && . "$FILE"
 +		fi
  	done
  	unset FILE
- }
+ fi
 
 --- a/package/base-files/files/lib/preinit/02_sysinfo
 +++ b/package/base-files/files/lib/preinit/02_sysinfo
@@ -86,6 +78,6 @@
  		echo "$(cat /proc/device-tree/model)" > /tmp/sysinfo/model
 +	sed -i "s/friendlyelec/friendlyarm/" /tmp/sysinfo/board_name
  }
- 
+
  boot_hook_add preinit_main do_sysinfo_generic
 
